CREATE TABLE Pedido
(
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS
IDENTITY,
pedido INTEGER NOT NULL,
dono VARCHAR (50) NOT NULL,
valor DOUBLE,
nome VARCHAR(50) NOT NULL,
atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);